name: manage-azure-policy-f2430981
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Require_a_tag_on_resource_groups_96670d01-0a4d-4649-9c89-2d3abc0a5025/**'
#      - .github/workflows/manage-azure-policy-f2430981.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f2430981}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Require_a_tag_on_resource_groups_96670d01-0a4d-4649-9c89-2d3abc0a5025/**
